description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: https://xdi8.top

paginate: 5
paginate_path: "/bulletin/page:num"
excerpt_separator: "\n##"
languages:
  - zh-Hans
  - en
default_lang: zh-Hans
fallback_canonical_to_default_lang: true
exclude_from_localization:
  - asset
  - css
  - js
  - fonts
  - sw.js
  - 404.html
  - CNAME
  - README.md
parallel_localization: false

collections:
  md:
    output: false

navigation:
  left:
    - key: navigation
      url: /navigation
    - key: about
      url: /about
    - key: wiki
      url: https://wiki.xdi8.top/
  right:
    - key: bulletin
      url: /bulletin
    - key: tutorials
      url: /tutorials
    - key: studio
      url: /studio

defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: post
