description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: https://xdi8.top

paginate: 5
paginate_path: "/blog/page:num"
languages:
  - zh-Hans
  - en
default_lang: zh-Hans
fallback_canonical_to_default_lang: true
exclude_from_localization:
  - css
  - js
  - 404.html
  - CNAME
  - README.md
parallel_localization: false

defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: post
