name: Deploy Jekyll site

on:
  push:
    branches: ["next"]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'
          bundler-cache: true
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        run: bundle exec jekyll build # --baseurl "${{ steps.pages.outputs.base_path }}"
        #env:
        #  JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  #deploy-pages:
  #  runs-on: ubuntu-latest
  #  needs: build
  #  steps:
  #    - name: Deploy to GitHub Pages
  #      id: deployment
  #      uses: actions/deploy-pages@v4
  #  environment:
  #    name: github-pages
  #    url: ${{ steps.deployment.outputs.page_url }}

  deploy-ftp:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: Extract tar
        run: |
          mkdir _site && tar -xvf artifact.tar -C _site
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          local-dir: ./_site/
          server: ${{ vars.FTP_SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ vars.SERVER_DIR }}
    environment:
      name: vudrux.site
      url: ${{ vars.DEPLOYMENT_URL }}
